# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: Default

steps:
- task: Ant@1
  inputs:
    workingDirectory: ''
    buildFile: 'build.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
- task: FortifySCA@7
  inputs:
    licenseFile: 'C:\Util\agent\fortify.license'
    runBuildTranslate: true
    applicationType: 'java'
    buildSourcePath: ''
    fortifySourceTranslate: 'src\my\Main\EightBall.java'
    fortifyBuildId: 'eightball'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: false
    scaDebug: false
    runFortifyScan: true
    fortifyScanType: 'LocalScan'
